SELECT COUNT(i.FISH_TYPE) AS FISH_COUNT,i.FISH_NAME
FROM (SELECT f.ID,f.FISH_TYPE,n.FISH_NAME
    FROM FISH_INFO f
    JOIN FISH_NAME_INFO n ON f.FISH_TYPE=n.FISH_TYPE)i
GROUP BY i.FISH_TYPE,i.FISH_NAME
ORDER BY FISH_COUNT DESC;