SELECT e.ID,
    CASE
        WHEN e.SIZE_OF_COLONY<=100 THEN 'LOW'
        WHEN e.SIZE_OF_COLONY>100&&e.SIZE_OF_COLONY<=1000 THEN 'MEDIUM'
        WHEN e.SIZE_OF_COLONY>=1001 THEN 'HIGH'
    END 
    AS SIZE
FROM ECOLI_DATA e
ORDER BY e.ID