SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i
WHERE  i.ANIMAL_ID NOT IN( 
        SELECT I.ANIMAL_ID
        FROM ANIMAL_INS I
        JOIN ANIMAL_OUTS o ON I.ANIMAL_ID = o.ANIMAL_ID
        ) 
ORDER BY i.DATETIME
LIMIT 3;