SELECT YEAR(ee.DIFFERENTIATION_DATE) AS YEAR, m.MAX_OF_COLONY-ee.SIZE_OF_COLONY AS YEAR_DEV,ee.ID
FROM (SELECT YEAR(e.DIFFERENTIATION_DATE) AS MAXYEAR,
       MAX(e.SIZE_OF_COLONY) AS MAX_OF_COLONY
        FROM ECOLI_DATA e
        GROUP BY YEAR(e.DIFFERENTIATION_DATE)) m
JOIN ECOLI_DATA ee ON YEAR(ee.DIFFERENTIATION_DATE) = m.MAXYEAR
ORDER BY YEAR,YEAR_DEV;
