SELECT  SUM(f.SCORE) AS SCORE,f.EMP_NO, f.EMP_NAME, f.POSITION, f.EMAIL
FROM(SELECT e.EMP_NO,e.EMP_NAME,e.POSITION,e.EMAIL,g.SCORE
    FROM HR_EMPLOYEES e
    JOIN HR_GRADE g ON e.EMP_NO=g.EMP_NO) f
GROUP BY f.EMP_NO
ORDER BY SUM(f.SCORE) DESC
LIMIT 1;
