SELECT b.CATEGORY, SUM(f.TOTAL_SALES) AS TOTAL_SALES
FROM (
     SELECT s.BOOK_ID, SUM(s.SALES) AS TOTAL_SALES
    FROM BOOK_SALES s
    WHERE MONTH(s.SALES_DATE)=1 && YEAR(s.SALES_DATE)=2022
    GROUP BY s.BOOK_ID
     ) f
JOIN BOOK b ON f.BOOK_ID=b.BOOK_ID
GROUP BY b.CATEGORY 
ORDER BY b.CATEGORY;
